Disable ARM wheel builds on Linux for now, since they're failing:
  ...
        running build_ext
        running build_rust
            Updating crates.io index
        cargo rustc --lib --message-format=json-render-diagnostics --manifest-path lib-rio/Cargo.toml --release -v --features pyo3/extension-module -- --crate-type cdylib
        error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path lib-rio/Cargo.toml --release -v --features pyo3/extension-module -- --crate-type cdylib` failed with code -9
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for breezy
  ERROR: Failed to build one or more wheels
  Failed to build breezy